name: xBossBar
main: dev.drygo.XBossBar.XBossBar
version: 1.1.0
api-version: 1.20
authors: [Drygo]
softdepend:
  - PlaceholderAPI
description: "Create, edit and show custom BossBars with a few commands, All on a single plugin."
website: https://modrinth.com/plugin/xbossbar
commands:
  xbossbar:
    description: "xBossBar plugin command."
    aliases: [xbb]
permissions:
  xbossbar.admin:
    default: false
    children:
      xbossbar.create:
        default: false
      xbossbar.settitle:
        default: false
      xbossbar.setstyle:
        default: false
      xbossbar.setcolor:
        default: false
      xbossbar.addplayer:
        default: false
      xbossbar.removeplayer:
        default: false
      xbossbar.remove:
        default: false
      xbossbar.info:
        default: false
      xbossbar.help:
        default: false